class ChampionList
	include Enumerable

	def each
	    yield [266,  "Aatrox"]
	    yield [412, "Thresh"] 
	    yield [23,   "Tryndamere"]
	    yield [79,  "Gragas"] 
	    yield [69,  "Cassiopeia"] 
	    yield [136,  "Aurelion Sol"] 
	    yield [13,  "Ryze"] 
	    yield [78,  "Poppy"] 
	    yield [14,  "Sion"] 
	    yield [1,  "Annie"] 
	    yield [202, "Jhin"] 
	    yield [43,  "Karma"] 
	    yield [111,  "Nautilus"] 
	    yield [240,  "Kled"] 
	    yield [99,  "Lux"] 
	    yield [103,  "Ahri"] 
	    yield [2, "Olaf"] 
	    yield [112, "Viktor"] 
	    yield [34,  "Anivia"] 
	    yield [27,  "Singed"] 
	    yield [86,  "Garen"] 
	    yield [127,  "Lissandra"] 
	    yield [57,  "Maokai"] 
	    yield [25,  "Morgana"] 
	    yield [28,  "Evelynn"] 
	    yield [105,  "Fizz"] 
	    yield [74,  "Heimerdinger"] 
	    yield [238,  "Zed"] 
	    yield [68,  "Rumble"] 
	    yield [82, "Mordekaiser"] 
	    yield [37,  "Sona"] 
	    yield [96,  "Kog'Maw"] 
	    yield [55,  "Katarina"] 
	    yield [117,  "Lulu"] 
	    yield [22, "Ashe"] 
	    yield [30,  "Karthus"] 
	    yield [12, "Alistar"] 
	    yield [122, "Darius"] 
	    yield [67,  "Vayne"] 
	    yield [110,  "Varus"] 
	    yield [77,  "Udyr"] 
	    yield [89,  "Leona"] 
	    yield [126,  "Jayce"] 
	    yield [134,  "Syndra"] 
	    yield [80,  "Pantheon"] 
	    yield [92, "Riven"] 
	    yield [121,  "Kha'Zix"] 
	    yield [42, "Corki"] 
	    yield [268,  "Azir"] 
	    yield [51,  "Caitlyn"] 
	    yield [76,  "Nidalee"] 
	    yield [85,  "Kennen"] 
	    yield [3,  "Galio"] 
	    yield [45,  "Veigar"] 
	    yield [432, "Bard"] 
	    yield [150,  "Gnar"] 
	    yield [90,  "Malzahar"] 
	    yield [104,  "Graves"] 
	    yield [254,  "Vi"] 
	    yield [10,  "Kayle"] 
	    yield [39,  "Irelia"] 
	    yield [64,  "Lee Sin"] 
	    yield [420,  "Illaoi"] 
	    yield [60,  "Elise"] 
	    yield [106,  "Volibear"] 
	    yield [20,  "Nunu"] 
	    yield [4,  "Twisted Fate"] 
	    yield [24,  "Jax"] 
	    yield [102, "Shyvana"] 
	    yield [429,  "Kalista"] 
	    yield [36,  "Dr. Mundo"] 
	    yield [427,  "Ivern"] 
	    yield [131,  "Diana"] 
	    yield [223,  "Tahm Kench"] 
	    yield [63,  "Brand"] 
	    yield [113,  "Sejuani"] 
	    yield [8,  "Vladimir"] 
	    yield [154,  "Zac"] 
	    yield [421,  "Rek'Sai"] 
	    yield [133,  "Quinn"] 
	    yield [84,  "Akali"] 
	    yield [163,  "Taliyah"] 
	    yield [18,  "Tristana"] 
	    yield [120,  "Hecarim"] 
	    yield [15,  "Sivir"] 
	    yield [236,  "Lucian"] 
	    yield [107,  "Rengar"] 
	    yield [19,  "Warwick"] 
	    yield [72, "Skarner"] 
	    yield [54,  "Malphite"] 
	    yield [157,  "Yasuo"] 
	    yield [101,  "Xerath"] 
	    yield [17,  "Teemo"] 
	    yield [75,  "Nasus"] 
	    yield [58,  "Renekton"] 
	    yield [119,  "Draven"] 
	    yield [35,  "Shaco"] 
	    yield [50,  "Swain"] 
	    yield [91,  "Talon"] 
	    yield [40,  "Janna"] 
	    yield [115,  "Ziggs"] 
	    yield [245,  "Ekko"] 
	    yield [61,  "Orianna"] 
	    yield [114,  "Fiora"] 
	    yield [9,  "Fiddlesticks"] 
	    yield [31,  "Cho'Gath"] 
	    yield [33,  "Rammus"] 
	    yield [7,  "LeBlanc"] 
	    yield [16,  "Soraka"] 
	    yield [26,  "Zilean"] 
	    yield [56,  "Nocturne"] 
	    yield [222, "Jinx"] 
	    yield [83,  "Yorick"] 
	    yield [6,  "Urgot"] 
	    yield [203,  "Kindred"] 
	    yield [21,  "Miss Fortune"] 
	    yield [62, "Wukong"] 
	    yield [53,  "Blitzcrank"] 
	    yield [98,  "Shen"] 
	    yield [201,  "Braum"] 
	    yield [5,  "Xin Zhao"] 
	    yield [29,  "Twitch"] 
	    yield [11,  "Master Yi"] 
	    yield [44,  "Taric"] 
	    yield [32, "Amumu"] 
	    yield [41,  "Gangplank"] 
	    yield [48,  "Trundle"] 
	    yield [38,  "Kassadin"] 
	    yield [161,  "Vel'Koz"] 
	    yield [143,  "Zyra"] 
	    yield [267,  "Nami"] 
	    yield [59,  "Jarvan IV"] 
	    yield [81,  "Ezreal"] 

# last 15 extra added
		yield [164,  "Cammille"] 
		yield [497,  "Rakan"] 
		yield [498,  "Xayah"] 
		yield [141,  "Kayn"] 
		yield [516,  "Ornn"] 
		yield [142,  "Zoe"] 
		yield [145,  "Kai'sa"] 
		yield [555,  "Pyke"] 
		yield [518,  "Neeko"] 
		yield [517,  "Sylas"] 
		yield [350,  "Yuumi"] 
		yield [246,  "Qiyana"] 
		yield [235,  "Senna"] 
		yield [523,  "Aphelios"] 
		yield [875,  "Sett"] 
	end
end
	
